create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text,
  company text,
  contact text,
  message text,
  source text not null default 'website',
  details jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists chat_history_conversation_idx on public.chat_history (conversation_id, created_at);

alter table public.leads enable row level security;
alter table public.chat_history enable row level security;

revoke all on public.leads from anon, authenticated;
revoke all on public.chat_history from anon, authenticated;

create table if not exists public.staff_profiles (
  id uuid default gen_random_uuid() primary key,
  staff_name text unique not null,
  role text not null,
  monthly_salary numeric not null,
  hourly_rate numeric not null,
  per_minute_rate numeric not null,
  created_at timestamptz default now()
);

insert into public.staff_profiles (staff_name, role, monthly_salary, hourly_rate, per_minute_rate)
values
  ('Jonathan', 'Garments Cutter & All-Around', 12000, 46.15, 0.7692),
  ('Linda', 'Sewer Supervisor & All-Around', 15000, 57.69, 0.9615)
on conflict (staff_name) do update set
  role = excluded.role,
  monthly_salary = excluded.monthly_salary,
  hourly_rate = excluded.hourly_rate,
  per_minute_rate = excluded.per_minute_rate;

create table if not exists public.staff_attendance (
  id uuid default gen_random_uuid() primary key,
  staff_name text not null,
  time_in timestamptz not null,
  time_out timestamptz,
  total_minutes numeric default 0,
  total_earned numeric default 0,
  created_at timestamptz default now()
);

alter table public.staff_profiles enable row level security;
alter table public.staff_attendance enable row level security;
create index if not exists staff_att_idx on public.staff_attendance (staff_name, time_in desc);
revoke all on public.staff_profiles from anon, authenticated;
revoke all on public.staff_attendance from anon, authenticated;

create table if not exists public.purchase_orders (
  id uuid default gen_random_uuid() primary key,
  po_number text unique not null,
  supplier_name text not null,
  material_type text not null,
  quantity_requested numeric not null,
  unit_cost numeric not null,
  total_cost numeric not null,
  status text not null default 'PENDING_APPROVAL',
  created_at timestamptz default now()
);

alter table public.purchase_orders enable row level security;
create index if not exists po_num_idx on public.purchase_orders (po_number);
revoke all on public.purchase_orders from anon, authenticated;

create table if not exists public.payment_verifications (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid,
  expected_amount numeric not null,
  detected_amount numeric,
  reference text,
  transaction_date text,
  recipient text,
  confidence numeric default 0,
  verified boolean not null default false,
  notes text,
  created_at timestamptz default now()
);

alter table public.payment_verifications enable row level security;
create index if not exists payment_verification_created_idx on public.payment_verifications (created_at desc);
revoke all on public.payment_verifications from anon, authenticated;

create table if not exists public.project_costings (
  id uuid default gen_random_uuid() primary key,
  project_name text,
  client_name text,
  company_name text,
  contact text,
  style text not null,
  quantity numeric not null,
  is_sample boolean not null default false,
  costing jsonb not null,
  total_cost numeric not null default 0,
  status text not null default 'PENDING_APPROVAL',
  created_at timestamptz default now()
);

alter table public.project_costings enable row level security;
create index if not exists project_costings_created_idx on public.project_costings (created_at desc);
revoke all on public.project_costings from anon, authenticated;

create table if not exists public.order_status_log (
  id uuid default gen_random_uuid() primary key,
  verification_id uuid references public.payment_verifications(id),
  status text not null,
  notes text,
  created_at timestamptz default now()
);

alter table public.order_status_log enable row level security;
create index if not exists order_status_created_idx on public.order_status_log (created_at desc);
revoke all on public.order_status_log from anon, authenticated;

create table if not exists public.material_inventory (
  id uuid default gen_random_uuid() primary key,
  material_name text unique not null,
  quantity_available numeric not null default 0,
  unit text not null,
  supplier_name text,
  updated_at timestamptz default now()
);

create table if not exists public.dispatch_requests (
  id uuid default gen_random_uuid() primary key,
  project_name text,
  pickup_address text not null,
  delivery_address text not null,
  contact_name text not null,
  contact_phone text not null,
  package_description text,
  status text not null default 'PENDING_APPROVAL',
  provider_response jsonb,
  approved_at timestamptz,
  created_at timestamptz default now()
);

alter table public.material_inventory enable row level security;
alter table public.dispatch_requests enable row level security;
create index if not exists dispatch_status_created_idx on public.dispatch_requests (status, created_at desc);
revoke all on public.material_inventory from anon, authenticated;
revoke all on public.dispatch_requests from anon, authenticated;

create table if not exists public.embroidery_jobs (
  id uuid default gen_random_uuid() primary key,
  project_name text,
  client_name text,
  company_name text,
  contact text,
  garment_style text,
  quantity numeric,
  placement text not null,
  width_inches numeric,
  height_inches numeric,
  stitch_count numeric,
  thread_colors jsonb default '[]'::jsonb,
  logo_image text,
  embroiderer_name text,
  embroiderer_contact text,
  notes text,
  status text not null default 'PENDING_DISPATCH',
  dispatched_at timestamptz,
  pickup_commitment_at timestamptz,
  pickup_alert_sent_at timestamptz,
  created_at timestamptz default now()
);

alter table public.embroidery_jobs add column if not exists pickup_commitment_at timestamptz;
alter table public.embroidery_jobs add column if not exists pickup_alert_sent_at timestamptz;
create index if not exists embroidery_jobs_pickup_commitment_idx
  on public.embroidery_jobs (pickup_commitment_at)
  where pickup_commitment_at is not null and pickup_alert_sent_at is null;

create table if not exists public.digitize_jobs (
  id uuid default gen_random_uuid() primary key,
  embroidery_job_id uuid references public.embroidery_jobs(id),
  source_image text not null,
  placement text,
  width_inches numeric,
  height_inches numeric,
  status text not null default 'PENDING_MANUAL_DIGITIZING',
  provider text,
  dst_file_url text,
  dst_file_base64 text,
  stitch_count numeric,
  notes text,
  created_at timestamptz default now()
);

alter table public.embroidery_jobs enable row level security;
alter table public.digitize_jobs enable row level security;
create index if not exists embroidery_jobs_status_idx on public.embroidery_jobs (status, created_at desc);
create index if not exists digitize_jobs_status_idx on public.digitize_jobs (status, created_at desc);

create table if not exists public.suppliers_directory (
  id uuid default gen_random_uuid() primary key,
  supplier_name text not null,
  category text not null check (category in ('fabric', 'accessories', 'embroidery')),
  materials_supplied jsonb default '[]'::jsonb,
  pricing_sheet jsonb default '{}'::jsonb,
  lead_time_days numeric,
  telegram_chat_id text,
  contact_info jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table public.suppliers_directory enable row level security;
create index if not exists suppliers_directory_category_idx on public.suppliers_directory (category);
revoke all on public.suppliers_directory from anon, authenticated;
revoke all on public.embroidery_jobs from anon, authenticated;
revoke all on public.digitize_jobs from anon, authenticated;

create table if not exists public.media_ad_generations (
  id uuid default gen_random_uuid() primary key,
  campaign_name text not null,
  model_id text not null,
  operation jsonb not null,
  status text not null default 'RUNNING' check (status in ('RUNNING', 'COMPLETED', 'FAILED')),
  video_storage_path text,
  approval_id uuid references public.media_ad_approvals(id),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.media_ad_generations enable row level security;
create index if not exists media_ad_generations_created_idx on public.media_ad_generations (created_at desc);
revoke all on public.media_ad_generations from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('media-ad-renders', 'media-ad-renders', false, 104857600, array['video/mp4'])
on conflict (id) do nothing;

create table if not exists public.media_ad_approvals (
  id uuid default gen_random_uuid() primary key,
  campaign_name text not null,
  status text not null default 'PENDING_APPROVAL' check (status in ('PENDING_APPROVAL', 'APPROVED', 'DECLINED', 'NOTIFICATION_FAILED')),
  decided_at timestamptz,
  decided_by_telegram_id text,
  created_at timestamptz not null default now()
);

alter table public.media_ad_approvals enable row level security;
create index if not exists media_ad_approvals_created_idx on public.media_ad_approvals (created_at desc);
revoke all on public.media_ad_approvals from anon, authenticated;

alter table public.staff_profiles add column if not exists telegram_chat_id text;
alter table public.staff_profiles add column if not exists link_code text;
alter table public.staff_profiles add column if not exists link_code_expires_at timestamptz;

create table if not exists public.staff_tasks (
  id uuid default gen_random_uuid() primary key,
  staff_name text not null,
  task_text text not null,
  priority text not null default 'normal' check (priority in ('normal', 'urgent', 'emergency')),
  status text not null default 'pending' check (status in ('pending', 'done')),
  due_at timestamptz,
  reminder_count integer not null default 0,
  last_reminded_at timestamptz,
  created_by text default 'CEO',
  completed_at timestamptz,
  created_at timestamptz default now()
);

alter table public.staff_tasks enable row level security;
create index if not exists staff_tasks_staff_status_idx on public.staff_tasks (staff_name, status, priority);
revoke all on public.staff_tasks from anon, authenticated;

revoke all on public.embroidery_jobs from anon, authenticated;
revoke all on public.digitize_jobs from anon, authenticated;
